### ISSUE TITLE
Needs a readme!

### ISSUE THREAD

**Issue by Frijol** [Local-Connectivity-Lab/Local-Connectivity-Lab-Old-Website#5]
As a community project, this should have a readme! Suggested sections:
* Link to site
* Short list of technologies in use
* How to set up to develop this site
* How to deploy (or explanation of CI)

**Comment by Frijol** [comment]
@sudheesh001 I'm happy to make the PR if you can drop some details here?

**Comment by dominickta** [comment]
Thanks for making this issue and bringing it up!
